name: usti_syn_gen

channels:
  - defaults

dependencies:
  - python=3.7.11
  - geopandas=0.9.0
  - tqdm=4.45.0
  - matplotlib=3.3.4
  - openpyxl=3.0.7
  - pip=21.2.2
  - sqlalchemy=1.4.22
  - xlrd=1.2.0
  - lxml=4.8.0
  - pip:
    - geopy==2.2.0    
    - synpp==1.2.1
    - simpledbf==0.2.6
    - osmium==3.2.0
